plugins {
    id 'com.android.application'
}

android {
    namespace 'com.alhaswa.app'
    compileSdk 35

    defaultConfig {
        applicationId 'com.alhaswa.app'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }
}

dependencies {
    implementation 'org.mapsforge:mapsforge-map-android:0.30.0'
    implementation 'org.mapsforge:mapsforge-map-reader:0.30.0'
    implementation 'org.mapsforge:mapsforge-core:0.30.0'
}
